### ISSUE TITLE
Loading multiple trees produces weird behavior 

### ISSUE THREAD

**Issue by raacampbell** [raacampbell/lasagna#164]
Problem description:

1. Load YH175 (or any) registered stack
2. File > load ingredient > tree load > traced cell 2 (all is OK, but I think it doesn't render until you start panning).
3. File > load ingredient > tree load > traced cell 3 (NOTHING LOADS)

Try again: load trace 1 then trace 2. Trace 2 loads, but there are lines linking segments that shouldn't be linked. 

Delete trace 2 and try loading 3. Nothing happens. 

Restart and load trace 3. All is fine.

**Comment by raacampbell** [comment]
Can re-reproduce the issue like this:

``` 
lasagna -im result.1.mhd -T YH175_traced_cells_tree_01.csv YH175_traced_cells_tree_02.csv 
```

**Comment by raacampbell** [comment]
The connection of inappropriate lines is possibly related to this line in lines.py:

```    pyqtObject.setData(x=data[:,0], y=data[:,1], 
                                pen=pg.mkPen(color=self.symbolBrush(), width=self.lineWidth), 
                                antialias=True,
                                connect="finite")
```
The connect="finite" is what I'm using to break up lines that are connected with a NaN. Removing that causes all trees to inappropriately connected. I reckon the issue is that the setting is being applied only to the first tree for some reason.

**Comment by raacampbell** [comment]
Also:
```
lasagna -im result.1.mhd -T YH175_traced_cells_tree_02.csv YH175_traced_cells_tree_01.csv 
```

Gives:
```
lasanga.addIngredient - Adding imagestack ingredient: result.1.mhd
Loading tree YH175_traced_cells_tree_02.csv

lasanga.addIngredient - Adding lines ingredient: YH175_traced_cells_tree_02.csv
Plotting object <pyqtgraph.graphicsItems.PlotCurveItem.PlotCurveItem object at 0x7f0314ad85a8>
Plotting object <pyqtgraph.graphicsItems.PlotCurveItem.PlotCurveItem object at 0x7f0314ad8640>
Plotting object <pyqtgraph.graphicsItems.PlotCurveItem.PlotCurveItem object at 0x7f0314ad86d8>
Loading tree YH175_traced_cells_tree_01.csv
Traceback (most recent call last):
  File "/home/rob/bin/lasagna", line 1276, in <module>
    pluginToStart=pluginToStart, embedConsole=args.C)
  File "/home/rob/bin/lasagna", line 1243, in main
    tasty.loadActions['tree_reader'].showLoadDialog(thisFname)
  File "/home/rob/Dropbox/home/work/TissueCyte/code/lasagna/IO/tree_reader_plugin.py", line 97, in showLoadDialog
    data = self.dataFromPath(dataTree,thisPath)
  File "/home/rob/Dropbox/home/work/TissueCyte/code/lasagna/IO/tree_reader_plugin.py", line 61, in dataFromPath
    z.append(tree.nodes[thisNode].data['z'])
KeyError: 1581

```

**Comment by raacampbell** [comment]
I think there's something odd about these two traces.... (02 and 03)

**Comment by raacampbell** [comment]
WEIRD:
```
lasagna -im result.1.mhd -T YH175_traced_cells_tree_01.csv YH175_traced_cells_tree_02.csv YH175_traced_cells_tree_01.csv
```

GIVES:
```
lasanga.addIngredient - Adding imagestack ingredient: result.1.mhd
Loading tree YH175_traced_cells_tree_01.csv
tree_reader_plugin.showLoadDialog - importing YH175_traced_cells_tree_01.csv
tree.importData importing file YH175_traced_cells_tree_01.csv
tree.importData read 1061 rows of data from YH175_traced_cells_tree_01.csv
tree_reader_plugin.showLoadDialog - found 154 segments <====NOTE THIS
Divided tree into 307 segments

lasanga.addIngredient - Adding lines ingredient: YH175_traced_cells_tree_01.csv
Loading tree YH175_traced_cells_tree_02.csv
tree_reader_plugin.showLoadDialog - importing YH175_traced_cells_tree_02.csv
tree.importData importing file YH175_traced_cells_tree_02.csv
tree.importData read 1674 rows of data from YH175_traced_cells_tree_02.csv
tree_reader_plugin.showLoadDialog - found 580 segments
Divided tree into 851 segments

lasanga.addIngredient - Adding lines ingredient: YH175_traced_cells_tree_02.csv
Loading tree YH175_traced_cells_tree_01.csv
tree_reader_plugin.showLoadDialog - importing YH175_traced_cells_tree_01.csv
tree.importData importing file YH175_traced_cells_tree_01.csv
tree.importData read 1061 rows of data from YH175_traced_cells_tree_01.csv
tree_reader_plugin.showLoadDialog - found 1006 segments  <=====NOW SEE THIS

```

WTF? It's the tree reader that's fucking up.

**Comment by raacampbell** [comment]
942d53d  recursive call of tree.findSegments was storing the previous contents of the input argument segments across calls. Not sure why it was doing that. Forced it to clear the value by wiping segments when the NodeID is zero.

**Comment by raacampbell** [comment]
This is what was wrong: 0ccb54b88c3d86834dd535505af530a59137c24a
