### ISSUE TITLE
MHD reading crashes Lasagna

### ISSUE THREAD

**Issue by raacampbell** [raacampbell/lasagna#187]
This has started happening recently. TIFF reading is fine. Error is:
```
Loading image stack /Volumes/data/MesoSPIM/190110_test_stacks_alex_brain_01/cereb_1024.mhd
Failed to find VTK. Falling back to built in (but slower) MHD reader
cereb_1024.raw
Traceback (most recent call last):
  File "./lasagna.py", line 480, in showStackLoadDialog
    self.loadImageStack(str(fname))
  File "./lasagna.py", line 421, in loadImageStack
    loadedImageStack = imageStackLoader.loadStack(fnameToLoad)
  File "/Users/rob/Desktop/lasagna/imageStackLoader.py", line 31, in loadStack
    return mhdRead(fname)
  File "/Users/rob/Desktop/lasagna/imageStackLoader.py", line 143, in mhdRead
    return mhdRead_fallback(fname)
  File "/Users/rob/Desktop/lasagna/imageStackLoader.py", line 208, in mhdRead_fallback
    return mhd_read_raw_file(fname,info)
  File "/Users/rob/Desktop/lasagna/imageStackLoader.py", line 288, in mhd_read_raw_file
    data = fid.read()
OSError: [Errno 22] Invalid argument
Abort trap: 6
```
And this happens with  365fae8

**Comment by raacampbell** [comment]
```
>>> with open('dssample_3AAV_cortex_Azimuth_181215_135102_10_10_02.raw','rb') as fid:
...   data = fid.read()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
OSError: [Errno 22] Invalid argument
```
Argh. WTF?

**Comment by raacampbell** [comment]
Works in Python 2.7 on this machine. Fails with Python 3.6.2. Something is fucked with that, I reckon. The code is correct.

**Comment by raacampbell** [comment]
Install v3.7 with Brew. Then re-install all the modules and stuff. Then it works.
